# Generated by Django 4.0.4 on 2022-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0002_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
